### ISSUE TITLE
import tweepy in chatty.py

### ISSUE THREAD

**Issue by pbinkley** [edsu/itstimeihadsometimealone#6]
I had to import tweepy in chatty.py, otherwise I got 

```
$ python3 chatty.py

Following your home timeline tweet (🐦) retweet (🔁)
Press CTRL-C to stop and output summary.

Traceback (most recent call last):
  File "chatty.py", line 47, in <module>
    for status in tweepy.Cursor(twitter.home_timeline, count=200).items(800):
NameError: name 'tweepy' is not defined
```

(in 34c3ed5)

**Comment by edsu** [comment]
Yes, sorry you caught it while it wasn't working. Hopefully the latest code fixes the problem for you? Also, I hope you are doing well Peter!

**Comment by pbinkley** [comment]
Fixed - thanks! And yes, we're doing ok  up here (trying to imagine what this would be like with young kids!)
